### ISSUE TITLE
bug in element

### ISSUE THREAD

**Issue by MEGRETP** [cgnieder/elements#2] opened 2017-06-12 10:25 UTC
Dear Clemens,

I found some small mistakes: 2 on French names for elements (Mo and Lu) and two on main isotopes (Li and Er):

I try to correct them by using: 

```latex
\setatomisotopes{3}{4,5,6,!7,8,9,10,11,12}
\setatomisotopes{68}{162,163,164,165,!166,167,168,169,170}
\setatomname[Molybdene]{42}{Molybd\`ene}
\setatomname[Lutecium]{71}{Lut\'ecium}
```

But if I put all four lines before `\begin{document}`, French name are corrected but main isotope numbers are empty for corrected values.

If I put all four lines after `\begin{document}`, French name are wrong but  main isotope numbers for corrected values are correct.

So I have to put 
```latex
\setatomisotopes{3}{4,5,6,!7,8,9,10,11,12}
\setatomisotopes{68}{162,163,164,165,!166,167,168,169,170}

```
before `\begin{document}` and
```latex
\setatomname[Molybdene]{42}{Molybd\`ene}
\setatomname[Lutecium]{71}{Lut\'ecium}
```
after `\begin{document}`

Rmk: if `\ttfamily`, the solution with the 4 lines after `\begin{document}` works.

Best regards,
Patrice

**Comment by cgnieder** [comment] 2017-06-12 16:06
I corrected the typos and isotope lists. The isotope lists are defined in the `sty` file so changing them in the preamble works.  The names, however, are set when the language of the document is determined and this happens at begin document.

```latex
\usepackage{elements}

\AtBeginDocument{
  \setatomisotopes{3}{4,5,6,!7,8,9,10,11,12}
  \setatomisotopes{68}{162,163,164,165,!166,167,168,169,170}
  \setatomname[Molybdene]{42}{Molybd\`ene}
  \setatomname[Lutecium]{71}{Lut\'ecium}
}

\begin{document}
```

would have worked.

This is completely independent from using any font or font family so I cannot believe the remark unless you show me a [MWE](https://tex.meta.stackexchange.com/q/228/).

**Comment by cgnieder** [comment] 2017-06-12 16:11
fixed in commit 2f964d5fbb6e55af99ffd1c7f6742011ec3b233b

**Closed as completed by cgnieder** 2017-06-12 16:11 UTC
Labels: bug

**Comment by MEGRETP** [comment] 2017-06-12 19:37
Thanks a lot.

Here is a small example of the problem with `\ttfamily` and `babel` `francais`: the first `\mainelementisotope` is empty.


\documentclass{book}
\usepackage[latin1]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[francais]{babel}

\usepackage{elements}
\begin{document}
\setatomisotopes{3}{4,5,6,!7,8,9,10,11,12}

main isotope: \mainelementisotope{3}

\ttfamily
main isotope: \mainelementisotope{3}
\end{document}

**Comment by cgnieder** [comment] 2017-06-13 08:35
This is much more interesting:

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[francais]{babel}
\usepackage{elements}

\begin{document}

\mainelementisotope{3}

text \mainelementisotope{3}

\end{document}
```

I am not sure what *exactly* happens but cause of the problem is that French `babel` makes `!` an active character. Making it other temporarily solves the problem:

```latex
\catcode`!=12
\setatomisotopes{3}{4,5,6,!7,8,9,10,11,12}
\catcode`!=13
```

solves the problem.

**Comment by MEGRETP** [comment] 2017-06-16 05:59
Dear Clemens,

Thanks.

Elements has been upgraded on CTAN but the error on the name of element 71

\DeclareAtomName[Lutetium]{71}{Lut\'etium}

is still there.  (replace t par c)

It should be:

\DeclareAtomName[Lutecium]{71}{Lut\'ecium}

**Comment by cgnieder** [comment] 2017-06-16 12:04
Oh, well… Thanks
